use_default_settings: true

general:
  instance_name: "Private SearXNG"

search:
  formats:
    - html
    - json

server:
  secret_key: "X7zL9qR2vB4mP6jN1wS8kC3fT5hG9aY0xV2uM4iE6oB8pZ1dQ3sK5nJ7rL9tW0"
  limiter: false
  image_proxy: false
  public_instance: false
